pool_list = [
    'WIN',
    'PLACE',
    'QUINELLA',
    'QUINELLA PLACE',
    'TIERCE',
    'TRIO',
    '5TH DOUBLE',
    '12TH DOUBLE TRIO',
    'TRIPLE TRIO',
    'TRIPLE TRIOConsolation',
    'TREBLE',
    'SIX UP',
    'FIRST 4',
    '1ST DOUBLE',
    '2ND DOUBLE',
    '3RD DOUBLE',
    '4TH DOUBLE',
    '1ST DOUBLE TRIO',
    '6TH DOUBLE',
    '7TH DOUBLE',
    '2ND DOUBLE TRIO',
    '8TH DOUBLE',
    '9TH DOUBLE',
    '10TH DOUBLE',
    '3RD DOUBLE TRIO',
    'JOCKEY CHALLENGE 1',
    'QUARTET',
    '3 PICK 1',
    'WINNING REGION',
    'WINNING TRAINER',
    'FORECAST',
    'TRAINER CHALLENGE 1',
    'JOCKEY CHALLENGE 2'
]